BookOcean.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookOcean.Repository.Abstract;
using BookOcean.Domain.Entities;

namespace BookOcean.Web.Controllers
{
    public class AccountController : Controller
    {
        IUser _user;
        public AccountController(IUser user)
        {
            _user = user;
        }
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if(_user.IsUserExist(model))
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Message = "User doesn't exist";
            return View();

        }

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(RegisterModel model)
        {
            _user.Register(model);
            return View();
        }
    }
}

BookOcean.Web/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookOcean.Repository.Abstract;
using BookOcean.Domain;

namespace BookOcean.Web.Controllers
{
    public class BookController : Controller
    {
        IBook _book;

        public BookController (IBook book)
        {
            this._book = book;
        }
        // GET: Book
        public ActionResult Index()
        {
            //_book.GetBooks();
            return View();
        }



        public ActionResult AddBook()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult AddBook(Book model)
        {
            _book.AddBook(model);
            //return RedirectToAction("AddBook");

            return View();
        }




        public ActionResult BindData()
        {
             
               
            return View(_book.GetBookBindData());
        } 


        public ActionResult Edit(int id)
        {

            Book book = _book.GetBook(id);
                return View(book);
            
        }
        [HttpPost]
        public ActionResult Edit(Book book)
        {
            //if(ModelState.IsValid)
            //{

            //this.entities.Entry(book).State= System.Data.EntityState.Modified;
            //db.SaveChanges();
            //return RedirectToAction("AddBook");
            //}
            //_book.EditBook(book);
            return View(_book.EditBook(book));

        }

        public ActionResult Delete(int id)
        {
            //Book book = this.ent.Books.Find(id);
            //db.Books.Remove(book);
           // db.SaveChanges();
            return View();
        }

        
    }
}

BookOcean.Web/Controllers/BookSetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookOcean.Domain;
using BookOcean.Repository.Abstract;

namespace BookOcean.Web.Controllers
{
    
    public class BookSetController : Controller
    {

        private IBookSet _bookset;
       public BookSetController(IBookSet bookset)
        {
            this._bookset = bookset;
        }
        // GET: BookSet
        public ActionResult Index()
        {
            return View(_bookset.GetBookByStandard(1));
        }

        public ActionResult Bookset()
        {

            return View(_bookset.GetClass(1));
        }
    }
}

BookOcean.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookOcean.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BookOcean.Web/Controllers/StandardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookOcean.Repository.Abstract;
using BookOcean.Domain;

namespace BookOcean.Web.Controllers
{
    public class StandardController : Controller
    {
        #region  Private Variables
        private IStandard _standard;
        #endregion

        #region
        public StandardController(IStandard standard)
        {
            this._standard = standard;
        }

        #endregion
        // GET: Standard
        public ActionResult Index()
        {
            return View(_standard.GetAllStandards());
        }

        public ActionResult Standard()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Standard(Standard model)
        {
            _standard.AddStandard(model);
            return View();
        }

    }
}

BookOcean.Web/Views/Book/AddBook.cshtml
@model BookOcean.Domain.Book

<script src="~/bs3/js/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script>
    $().ready(function () {
        // validate the comment form when it is submitted
        //$("#commentForm").validate();

        // validate signup form on keyup and submit
       

      
    });

    </script>

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Book
                <span class="tools pull-right">
                    <a class="fa fa-chevron-down" href="javascript:;"></a>
                    <a class="fa fa-cog" href="javascript:;"></a>
                    <a class="fa fa-times" href="javascript:;"></a>
                </span>
            </header>
            <div class="panel-body">
                <div class="form">

                    @using (Ajax.BeginForm("AddBook", "Book", new AjaxOptions {HttpMethod="POST",OnSuccess="AddSuccess" },new{@class="cmxform form-horizontal" , @id = "signupaForm" }))
                    {

                        <div class="form-group ">
                            <label for="firstname" class="control-label col-lg-3">BookName</label>
                            <div class="col-lg-6">

                                @Html.TextBoxFor(x=>x.BookName, new{@class= " form-control", @id = "firstname", @name="firstname" })
                                @Html.ValidationMessageFor(x=>x.BookName)
                            </div>
                        </div>
                        <div class="form-group ">
                            <label for="lastname" class="control-label col-lg-3">Publication</label>
                            <div class="col-lg-6">

                                @Html.TextBoxFor(x=>x.Publication,new { @class= " form-control" ,@id = "lastname", @name="Lastname" })
                                @Html.ValidationMessageFor(x => x.Publication)
                            </div>
                        </div>
                        <div class="form-group ">
                            <label for="username" class="control-label col-lg-3">Edition</label>
                            <div class="col-lg-6">

                                @Html.TextBoxFor(x => x.Edition, new { @class = " form-control", @id = "lastname", @name = "Lastname" })
                                @Html.ValidationMessageFor(x => x.Edition)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-6">
                                <button class="btn btn-primary" type="submit">ADD</button>
                                <button class="btn btn-danger btnClose" type="button">Close</button>
                            </div>
                        </div>




                    }
                </div>
            </div>
        </section>
    </div>
</div>

BookOcean.Web/Views/Book/Edit.cshtml
@model BookOcean.Domain.Book
@{
    ViewBag.Title = "Edit";

    Layout = "~/Views/Shared/_Layout.cshtml";

}






<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Form validations
                <span class="tools pull-right">
                    <a class="fa fa-chevron-down" href="javascript:;"></a>
                    <a class="fa fa-cog" href="javascript:;"></a>
                    <a class="fa fa-times" href="javascript:;"></a>
                </span>
            </header>
            <div class="panel-body">
                <div class=" form">
                  

                        @using (Html.BeginForm("Edit", "Book", FormMethod.Post))
                        {
                        <div class="form-group ">
                            <label for="cname" class="control-label col-lg-3">BookName (required)</label>
                            <div class="col-lg-6">

                                @*<input class=" form-control" id="cname" name="name" minlength="2" type="text" required />*@
                                
                                @Html.TextBoxFor(x => x.BookName, new { @class = " form-control", @id = "cname", @name = "name", minlength = "2" })
                                @Html.ValidationMessageFor(x => x.BookName)

                            </div>
                        </div>
                        <div class="form-group ">
                            <label for="cemail" class="control-label col-lg-3">Publication (required)</label>
                            <div class="col-lg-6">
                                @*<input class="form-control " id="cemail" type="email" name="email" required />*@

                                @Html.TextBoxFor(x => x.Publication, new { @class = " form-control", @id = "cname", @name = "email", minlength = "2", })
                                @Html.ValidationMessageFor(x => x.BookName)



                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="ccomment" class="control-label col-lg-3">Edition (required)</label>
                            <div class="col-lg-6">
                                @*<textarea class="form-control " id="ccomment" name="comment" required></textarea>*@

                                @Html.TextBoxFor(x => x.Edition, new { @class = " form-control", @id = "cname", @name = "name", minlength = "2", })
                                @Html.ValidationMessageFor(x => x.Edition)
                                @Html.HiddenFor(x => x.BookId)

                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-6">
                                <button class="btn btn-primary" type="submit">UPDATE</button>
                                
                            </div>
                        </div>

                        }
                  
                </div>
            </div>
        </section>







    </div>


    
    <table>
        <thead>
            <tr>
                <th>
                    @Html.Label("BookName");
                </th>
                <th>@Html.Label("Publication")</th>
                <th>@Html.Label("Edition")</th>
            </tr>

        </thead>

        
        
       @* @{List<BookOcean.Domain.Book> book = ViewBag.Books;*@



            @foreach (var item in Model)
            {
            <tr>

                <td>@item.BookName</td>
                <td>@item.Publication</td>
                <td>@item.Edition</td>
                <td>
                    
                    |@Html.ActionLink("Edit", "Edit", new { Id = item.Id })  |

                   @Html.ActionLink("Delete", "Delete", new { Id = item.Id }, new { onclick = "return confirm('Do You Want to Delete');" })


                </td>

            </tr>
            }


       @* }@*@

        
    </table>

</div>

BookOcean.Web/Views/Book/Index.cshtml
<link href="~/Scripts/bootstrap-table.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap-table.js"></script>

<script src="~/Scripts/Custom/Book.js"></script>

    <div class="addBook">
        @Html.Partial("AddBook")
    </div>
   
<div id="custom-toolbar" class="form-inline">
                <div class="form-group">
                
                <input class="form-control search" id="BookName" placeholder="Unit Name" type="text" name="Drugname">
                </div>

    <div class="form-group">
                
                    <input type="button" id="btnAdd" class="btn btn-primary" value="Add Book">
                </div>
    <a class="btn btn-danger" data-toggle="modal" href="#myModal3">
        Alert !
    </a>
    </div>

<table class="table table-hover" data-url='#custom-toolbar' data-toolbar="#post" data-show-columns="true" data-show-filter="true" data-click-to-select="true"
       id="grid">
    <thead>

    </thead>
</table>

BookOcean.Web/Views/BookSet/Bookset.cshtml
@model BookOcean.Domain.BookSet
@{
    ViewBag.Title = "Bookset";
}


<script>

    $(document).ready(function()
    {
        $("#Class").change(function(){
        
            $.ajax({ 
                url:"/BookSet/Bookset",
                type:"POST",
                data:{classId: $(this).val()},
                success:function(data){
                    $("").empty();
                    $("").html(data);
                }


                
            })
        })
    })
    

</script>






<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Select2 Components
                <span class="tools pull-right">
                    <a class="fa fa-chevron-down" href="javascript:;"></a>
                    <a class="fa fa-cog" href="javascript:;"></a>
                    <a class="fa fa-times" href="javascript:;"></a>
                </span>
            </header>
            <div class="panel-body">
                <form class="form-horizontal" action="#">
                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label">Basic select</label>
                        <div class="col-lg-6">
                            <select class="form-control" style="width: 300px" id="source">


                                @Html.DropDownList("Class",new SelectList(ViewBag.Class,"ClassId","Name"),"Select", new { @class = "form-control" })

                            </select>
                        </div>
                    </div>
                    
                   
                </form>
            </div>
        </section>
    </div>
</div>

BookOcean.Web/Views/BookSet/Index.cshtml
@model IEnumerable<BookOcean.Domain.Book>

@{
    ViewBag.Title = "Index";
   // Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Index</h2>


@*<table>
    <thead>
        <th>Class Name</th>

    <th>Book Name</th>
    <th>Publication</th>
    
    <th>Price</th>
    
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Standard.ClassName</td>
            <td>@item.BookName</td>
            <td>@item.Publication</td>
            <td>@item.SalePrice</td>

        </tr>
    }


</table>*@

BookOcean.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BookOcean.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BookOcean.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

BookOcean.Web/Views/Standard/Index.cshtml
@model IEnumerable<BookOcean.Domain.Standard>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Index</h2>

<table>
    <thead>
    <th>Class Name</th>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ClassName</td>
        </tr>
    }


</table>

BookOcean.Web/Views/Standard/Standard.cshtml
@model BookOcean.Domain.Standard


<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Advanced Form validations
                <span class="tools pull-right">
                    <a class="fa fa-chevron-down" href="javascript:;"></a>
                    <a class="fa fa-cog" href="javascript:;"></a>
                    <a class="fa fa-times" href="javascript:;"></a>
                </span>
            </header>
            <div class="panel-body">
                <div class="form">

                    @using (Html.BeginForm("Standard","Standard", FormMethod.Post, new { @class = "cmxform form-horizontal", @id = "signupForm" }))
                    {

                        <div class="form-group ">
                            <label for="firstname" class="control-label col-lg-3">ClassName</label>
                            <div class="col-lg-6">

                                @Html.TextBoxFor(x => x.ClassName, new { @class = " form-control", @id = "firstname", @name = "firstname" })
                                @Html.ValidationMessageFor(x => x.ClassName)
                            </div>
                        </div>
                        
                        

                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-6">
                                <button class="btn btn-primary" type="submit">ADD</button>
                            </div>
                        </div>




                    }
                </div>
            </div>
        </section>
    </div>
</div>